import Head from "next/head"
import { Site } from "../components/Layouts/Site"
import React from "react"

export default function Home() {
	return (
		<React.Fragment>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Site />
			</main>
		</React.Fragment>
	)
}
