import Head from 'next/head'
import Image from 'next/image'
import { NavBar } from '../components/NavBar/NavBar'
import { Grid, GridItem} from '@chakra-ui/layout'
import React from 'react'

export default function Home() {
  return (
      <React.Fragment>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <Grid w = {'100%'} h = {'100%'} templateRows = 'repeat(10, 1fr)' templateColumns = 'repeat(10, 1fr)'>
              <GridItem colSpan = {2} rowSpan = {2}>
                <NavBar/>
              </GridItem>
            </Grid>
          </main>
      </React.Fragment>
  )
}
